import Mathlib
import Jsp827.Tower.Basic

/-!
# Separating a set from a translate (Avila–Candela Proposition 2.1)

Let `f, g` be measure-preserving endomorphisms of a probability space that agree only on a
null set.  Then inside `f ⁻¹' Y` there is a measurable `B` with `μ B ≥ (μ Y − ε)/4` and
`f ⁻¹' B` disjoint from `g ⁻¹' B`.

As in the paper, `f` and `g` are assumed to commute; this is part of the standing
hypotheses there (the endomorphisms come from an action of `ℕ^d`) and it is what makes the
final disjointness argument work.

Proof (AC Prop 2.1 / Lemma 2.2): choose a countable family of measurable sets separating
points (`HasCountableSeparatingOn X MeasurableSet univ`); the finite partitions `P_r`
generated by the first `r` sets refine each other and separate points, so
`Ω_r := ⋃_{A ∈ P_r} f⁻¹A ∩ g⁻¹A` decreases to `{f = g}` and `μ Ω_r → 0`.  The atoms of `P_r`
are the fibres of `signPattern S r`.  Colouring them randomly (each atom coloured `true`
independently with probability `1/2`) and writing `C` for the union of the `true` atoms, the
expected measure of `f⁻¹(Y ∩ C) \ g⁻¹C` is at least `(μ Y − μ Ω_r)/4`, so some colouring
works, and `B := f⁻¹(Y ∩ C) \ g⁻¹C` satisfies `f⁻¹B ∩ g⁻¹B = ∅` because `f` and `g` commute.
-/

open MeasureTheory Set

open scoped ENNReal

namespace RokhlinTower

variable {X : Type*} [MeasurableSpace X] {μ : Measure X}

/-- Counting the random subsets used in the averaging argument: for `σ ≠ τ` in a finite type
`K`, exactly a quarter of the Boolean colourings `c : K → Bool` satisfy `c σ = true` and
`c τ = false`. -/
lemma sum_ite_eq_card {K : Type*} [Fintype K] [DecidableEq K] {σ τ : K} (hστ : σ ≠ τ) :
    ∑ c : K → Bool, (if c σ = true ∧ c τ = false then (4 : ℝ) else 0)
      = (Fintype.card (K → Bool) : ℝ) := by
  classical
  set F : K → Bool → ℝ := fun i b ↦
    if i = σ then (if b then 2 else 0) else if i = τ then (if b then 0 else 2) else 1 with hF
  have hprod : ∀ c : K → Bool,
      ∏ i : K, F i (c i) = if c σ = true ∧ c τ = false then (4 : ℝ) else 0 := by
    intro c
    have h1 : F σ (c σ) = if c σ = true then (2 : ℝ) else 0 := by simp [hF]
    have h2 : F τ (c τ) = if c τ = true then (0 : ℝ) else 2 := by simp [hF, Ne.symm hστ]
    rw [← Finset.prod_subset (Finset.subset_univ ({σ, τ} : Finset K)) ?_]
    · rw [Finset.prod_pair hστ, h1, h2]
      by_cases hσ : c σ = true <;> by_cases hτ : c τ = true <;> simp_all
      norm_num
    · intro i _ hi
      simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hi
      simp [hF, hi.1, hi.2]
  have hsum : ∀ i : K, ∑ b : Bool, F i b = 2 := by
    intro i
    rcases eq_or_ne i σ with h | h
    · simp [hF, h]
    · rcases eq_or_ne i τ with h' | h' <;> simp [hF, h, h']
  calc ∑ c : K → Bool, (if c σ = true ∧ c τ = false then (4 : ℝ) else 0)
      = ∑ c : K → Bool, ∏ i : K, F i (c i) := by simp [hprod]
    _ = ∏ i : K, ∑ b : Bool, F i b := (Fintype.prod_sum F).symm
    _ = (Fintype.card (K → Bool) : ℝ) := by
        rw [Finset.prod_congr rfl fun i _ ↦ hsum i, Finset.prod_const, Finset.card_univ,
          Fintype.card_fun, Fintype.card_bool]
        push_cast
        ring

/-- The measure of `W` intersected with the preimage of a finite set of values splits as a
sum over the fibres. -/
lemma toReal_measure_inter_fiber [IsFiniteMeasure μ] {ι : Type*} [DecidableEq ι] {w : X → ι}
    (hw : ∀ i : ι, MeasurableSet {x : X | w x = i}) {W : Set X} (hW : MeasurableSet W)
    (T : Finset ι) :
    (μ (W ∩ {x : X | w x ∈ T})).toReal = ∑ i ∈ T, (μ (W ∩ {x : X | w x = i})).toReal := by
  have hUnion : W ∩ {x : X | w x ∈ T} = ⋃ i ∈ T, W ∩ {x : X | w x = i} := by
    ext x
    refine ⟨fun h ↦ Set.mem_iUnion₂.2 ⟨w x, h.2, h.1, rfl⟩, fun h ↦ ?_⟩
    obtain ⟨i, hi, hxW, hxi⟩ := Set.mem_iUnion₂.1 h
    refine ⟨hxW, ?_⟩
    show w x ∈ T
    rw [show w x = i from hxi]
    exact hi
  have hd : (T : Set ι).PairwiseDisjoint fun i ↦ W ∩ {x : X | w x = i} := by
    intro i _ j _ hij
    refine Set.disjoint_left.2 fun x hx hx' ↦ hij ?_
    exact hx.2.symm.trans hx'.2
  rw [hUnion, measure_biUnion_finset hd fun i _ ↦ hW.inter (hw i),
    ENNReal.toReal_sum fun i _ ↦ measure_ne_top μ _]

/-- **Averaging step (Avila–Candela Lemma 2.2).**  If `u, v : X → ι` have measurable fibres in
a finite type `ι`, then some Boolean colouring `c` of `ι` separates `u` from `v` on at least a
quarter of `W`, up to the set where `u` and `v` agree. -/
lemma exists_colouring [IsFiniteMeasure μ] {ι : Type*} [Fintype ι] [DecidableEq ι] {u v : X → ι}
    (hu : ∀ i : ι, MeasurableSet {x : X | u x = i}) (hv : ∀ i : ι, MeasurableSet {x : X | v x = i})
    {W : Set X} (hW : MeasurableSet W) :
    ∃ c : ι → Bool, (μ W).toReal - (μ {x : X | u x = v x}).toReal
      ≤ 4 * (μ (W ∩ {x : X | c (u x) = true ∧ c (v x) = false})).toReal := by
  classical
  set w : X → ι × ι := fun x ↦ (u x, v x) with hw
  have hwfib : ∀ p : ι × ι, MeasurableSet {x : X | w x = p} := by
    intro p
    have : {x : X | w x = p} = {x : X | u x = p.1} ∩ {x : X | v x = p.2} := by
      ext x; simp [hw, Prod.ext_iff]
    rw [this]
    exact (hu p.1).inter (hv p.2)
  set m : ι × ι → ℝ := fun p ↦ (μ (W ∩ {x : X | w x = p})).toReal
  set N : ℝ := (Fintype.card (ι → Bool) : ℝ) with hN
  have hN0 : 0 ≤ N := by positivity
  have hdiag : ∑ p ∈ Finset.univ.filter fun p : ι × ι ↦ p.1 = p.2, m p
      = (μ (W ∩ {x : X | u x = v x})).toReal := by
    rw [← toReal_measure_inter_fiber hwfib hW _]
    congr 2
    ext x
    simp [hw]
  have htot : ∑ p : ι × ι, m p = (μ W).toReal := by
    rw [← toReal_measure_inter_fiber hwfib hW Finset.univ]
    congr 2
    simp
  have hcol : ∀ c : ι → Bool,
      (μ (W ∩ {x : X | c (u x) = true ∧ c (v x) = false})).toReal
        = ∑ p ∈ Finset.univ.filter fun p : ι × ι ↦ c p.1 = true ∧ c p.2 = false, m p := by
    intro c
    rw [← toReal_measure_inter_fiber hwfib hW _]
    congr 2
    ext x
    simp [hw]
  have hrw : ∑ c : ι → Bool, 4 * (μ (W ∩ {x : X | c (u x) = true ∧ c (v x) = false})).toReal
      = ∑ p : ι × ι, (∑ c : ι → Bool,
          (if c p.1 = true ∧ c p.2 = false then (4 : ℝ) else 0)) * m p := by
    simp only [hcol, Finset.mul_sum, Finset.sum_filter]
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun p _ ↦ ?_
    rw [Finset.sum_mul]
    exact Finset.sum_congr rfl fun c _ ↦ by split <;> ring
  have hlow : ∑ p : ι × ι, (if p.1 = p.2 then (0 : ℝ) else N * m p)
      ≤ ∑ p : ι × ι, (∑ c : ι → Bool,
          (if c p.1 = true ∧ c p.2 = false then (4 : ℝ) else 0)) * m p := by
    refine Finset.sum_le_sum fun p _ ↦ ?_
    rcases eq_or_ne p.1 p.2 with h | h
    · simp [h]
    · rw [sum_ite_eq_card h, ← hN]
      simp [h]
  have hsplit : ∑ p : ι × ι, (if p.1 = p.2 then (0 : ℝ) else N * m p)
      = N * ((μ W).toReal - (μ (W ∩ {x : X | u x = v x})).toReal) := by
    have h1 : ∑ p ∈ Finset.univ.filter fun p : ι × ι ↦ p.1 = p.2, m p
        + ∑ p ∈ Finset.univ.filter fun p : ι × ι ↦ ¬ p.1 = p.2, m p = ∑ p : ι × ι, m p :=
      Finset.sum_filter_add_sum_filter_not _ _ _
    have h2 : ∑ p : ι × ι, (if p.1 = p.2 then (0 : ℝ) else N * m p)
        = ∑ p ∈ Finset.univ.filter fun p : ι × ι ↦ ¬ p.1 = p.2, N * m p := by
      rw [Finset.sum_filter]
      exact Finset.sum_congr rfl fun p _ ↦ by split <;> simp_all
    rw [h2, ← Finset.mul_sum, ← htot, ← hdiag]
    congr 1
    linarith [h1]
  have hmono : (μ (W ∩ {x : X | u x = v x})).toReal ≤ (μ {x : X | u x = v x}).toReal :=
    ENNReal.toReal_mono (measure_ne_top μ _) (measure_mono Set.inter_subset_right)
  have hkey : ∑ _c : ι → Bool, ((μ W).toReal - (μ {x : X | u x = v x}).toReal)
      ≤ ∑ c : ι → Bool, 4 * (μ (W ∩ {x : X | c (u x) = true ∧ c (v x) = false})).toReal := by
    calc ∑ _c : ι → Bool, ((μ W).toReal - (μ {x : X | u x = v x}).toReal)
        = N * ((μ W).toReal - (μ {x : X | u x = v x}).toReal) := by
          rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul, hN]
      _ ≤ N * ((μ W).toReal - (μ (W ∩ {x : X | u x = v x})).toReal) := by
          exact mul_le_mul_of_nonneg_left (by linarith) hN0
      _ = ∑ p : ι × ι, (if p.1 = p.2 then (0 : ℝ) else N * m p) := hsplit.symm
      _ ≤ ∑ p : ι × ι, (∑ c : ι → Bool,
            (if c p.1 = true ∧ c p.2 = false then (4 : ℝ) else 0)) * m p := hlow
      _ = _ := hrw.symm
  obtain ⟨c, -, hc⟩ := Finset.exists_le_of_sum_le Finset.univ_nonempty hkey
  exact ⟨c, hc⟩

/-- The `Bool`-valued pattern recording membership of `x` in the first `r` sets of the family
`S`; its fibres are the atoms of the finite partition generated by `S 0, …, S (r - 1)`. -/
noncomputable def signPattern (S : ℕ → Set X) (r : ℕ) (x : X) : Fin r → Bool :=
  fun i ↦ @decide (x ∈ S i) (Classical.propDecidable _)

omit [MeasurableSpace X] in
/-- Two points have the same level-`r` pattern iff they are not separated by any of the first
`r` sets. -/
lemma signPattern_eq_iff {S : ℕ → Set X} {r : ℕ} {x y : X} :
    signPattern S r x = signPattern S r y ↔ ∀ i : Fin r, (x ∈ S i ↔ y ∈ S i) := by
  simp [signPattern, funext_iff, decide_eq_decide]

/-- The atoms of the level-`r` partition are measurable. -/
lemma measurableSet_signPattern_eq {S : ℕ → Set X} (hS : ∀ n : ℕ, MeasurableSet (S n)) (r : ℕ)
    (σ : Fin r → Bool) : MeasurableSet {x : X | signPattern S r x = σ} := by
  have hEq : {x : X | signPattern S r x = σ} = ⋂ i : Fin r, (if σ i then S i else (S i)ᶜ) := by
    ext x
    rw [Set.mem_iInter]
    show signPattern S r x = σ ↔ ∀ i : Fin r, x ∈ if σ i then S i else (S i)ᶜ
    rw [funext_iff]
    exact forall_congr' fun i ↦ by
      rcases Bool.eq_false_or_eq_true (σ i) with h | h <;> rw [h] <;> simp [signPattern]
  rw [hEq]
  exact MeasurableSet.iInter fun i ↦ by cases σ i <;> simp [hS]

/-- A union of atoms of the level-`r` partition is measurable. -/
lemma measurableSet_signPattern_mem {S : ℕ → Set X} (hS : ∀ n : ℕ, MeasurableSet (S n)) {r : ℕ}
    (T : Set (Fin r → Bool)) : MeasurableSet {x : X | signPattern S r x ∈ T} := by
  have hEq : {x : X | signPattern S r x ∈ T} = ⋃ σ ∈ T, {x : X | signPattern S r x = σ} := by
    ext x
    refine ⟨fun h ↦ Set.mem_iUnion₂.2 ⟨_, h, rfl⟩, fun h ↦ ?_⟩
    obtain ⟨σ, hσ, hx⟩ := Set.mem_iUnion₂.1 h
    show signPattern S r x ∈ T
    rw [show signPattern S r x = σ from hx]
    exact hσ
  rw [hEq]
  exact MeasurableSet.biUnion T.to_countable fun σ _ ↦ measurableSet_signPattern_eq hS r σ

/-- **Avila–Candela Proposition 2.1.** -/
theorem exists_separated_subset [IsProbabilityMeasure μ]
    [HasCountableSeparatingOn X MeasurableSet univ]
    {f g : X → X} (hf : MeasurePreserving f μ μ) (hg : MeasurePreserving g μ μ)
    (hcomm : ∀ x : X, f (g x) = g (f x))
    (hfg : μ {x | f x = g x} = 0) {Y : Set X} (hY : MeasurableSet Y) {ε : ℝ} (hε : 0 < ε) :
    ∃ B : Set X, MeasurableSet B ∧ B ⊆ f ⁻¹' Y ∧
      (μ Y).toReal - ε ≤ 4 * (μ B).toReal ∧ Disjoint (f ⁻¹' B) (g ⁻¹' B) := by
  classical
  obtain ⟨S, hSm, hSsep⟩ := exists_seq_separating X MeasurableSet.empty univ
  set Ω : ℕ → Set X := fun r ↦ {x : X | signPattern S r (f x) = signPattern S r (g x)}
  have hΩmeas : ∀ r : ℕ, MeasurableSet (Ω r) := by
    intro r
    have hEq : Ω r = ⋃ σ : Fin r → Bool,
        f ⁻¹' {y : X | signPattern S r y = σ} ∩ g ⁻¹' {y : X | signPattern S r y = σ} := by
      ext x
      refine ⟨fun hx ↦ Set.mem_iUnion.2 ⟨signPattern S r (f x), rfl, hx.symm⟩, fun hx ↦ ?_⟩
      obtain ⟨σ, h1, h2⟩ := Set.mem_iUnion.1 hx
      exact h1.trans h2.symm
    rw [hEq]
    exact MeasurableSet.iUnion fun σ ↦
      ((measurableSet_signPattern_eq hSm r σ).preimage hf.measurable).inter
        ((measurableSet_signPattern_eq hSm r σ).preimage hg.measurable)
  have hanti : Antitone Ω := by
    intro r r' hrr' x hx
    exact signPattern_eq_iff.2 fun i ↦ signPattern_eq_iff.1 hx ⟨i, i.2.trans_le hrr'⟩
  have hzero : μ (⋂ r, Ω r) = 0 := by
    refine measure_mono_null (fun x hx ↦ ?_) hfg
    refine hSsep (f x) (Set.mem_univ _) (g x) (Set.mem_univ _) fun n ↦ ?_
    exact signPattern_eq_iff.1 (Set.mem_iInter.1 hx (n + 1)) ⟨n, Nat.lt_succ_self n⟩
  have hlim : Filter.Tendsto (fun r ↦ μ (Ω r)) Filter.atTop (nhds 0) := by
    have h := tendsto_measure_iInter_atTop (μ := μ) (fun r ↦ (hΩmeas r).nullMeasurableSet)
      hanti ⟨0, measure_ne_top μ _⟩
    rw [hzero] at h
    exact h
  obtain ⟨r, hr⟩ := (hlim.eventually_lt_const (ENNReal.ofReal_pos.2 hε)).exists
  have hrε : (μ {x : X | signPattern S r (f x) = signPattern S r (g x)}).toReal < ε :=
    ENNReal.toReal_lt_of_lt_ofReal hr
  have hufib : ∀ σ : Fin r → Bool, MeasurableSet {x : X | signPattern S r (f x) = σ} :=
    fun σ ↦ (measurableSet_signPattern_eq hSm r σ).preimage hf.measurable
  have hvfib : ∀ σ : Fin r → Bool, MeasurableSet {x : X | signPattern S r (g x) = σ} :=
    fun σ ↦ (measurableSet_signPattern_eq hSm r σ).preimage hg.measurable
  have hW : MeasurableSet (f ⁻¹' Y) := hY.preimage hf.measurable
  obtain ⟨c, hc⟩ := exists_colouring (μ := μ) (u := fun x ↦ signPattern S r (f x))
    (v := fun x ↦ signPattern S r (g x)) hufib hvfib hW
  refine ⟨f ⁻¹' Y ∩ {x : X | c (signPattern S r (f x)) = true ∧
    c (signPattern S r (g x)) = false}, ?_, Set.inter_subset_left, ?_, ?_⟩
  · exact hW.inter (((measurableSet_signPattern_mem hSm {σ | c σ = true}).preimage
      hf.measurable).inter ((measurableSet_signPattern_mem hSm {σ | c σ = false}).preimage
      hg.measurable))
  · have hpre : (μ (f ⁻¹' Y)).toReal = (μ Y).toReal := by
      rw [hf.measure_preimage hY.nullMeasurableSet]
    rw [hpre] at hc
    linarith
  · refine Set.disjoint_left.2 fun x hxf hxg ↦ ?_
    have h1 : c (signPattern S r (g (f x))) = false := hxf.2.2
    have h2 : c (signPattern S r (f (g x))) = true := hxg.2.1
    rw [hcomm x, h1] at h2
    exact Bool.false_ne_true h2

end RokhlinTower
