import MerLeanExperiment.CertificateKernel

/-! Generated from the actual pinned z8direct_triangle_cycle5-trim CNF/LRAT data.
The generator is untrusted: every computation and inference is kernel checked. -/
namespace CochromaticTwenty.Certificates.Z8DirectTriangleCycle5
open Std.Sat Std.Tactic.BVDecide.LRAT Std.Tactic.BVDecide.LRAT.Internal
open CochromaticTwenty.CertificateKernel
set_option maxRecDepth 100000
set_option maxHeartbeats 10000000
def c1 : DefaultClause 16 := directClause [(⟨7, by decide⟩, false), (⟨8, by decide⟩, false), (⟨14, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c2 : DefaultClause 16 := directClause [(⟨7, by decide⟩, true), (⟨9, by decide⟩, true), (⟨13, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c3 : DefaultClause 16 := directClause [(⟨7, by decide⟩, true), (⟨10, by decide⟩, true), (⟨13, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c4 : DefaultClause 16 := directClause [(⟨8, by decide⟩, false), (⟨9, by decide⟩, false), (⟨12, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c5 : DefaultClause 16 := directClause [(⟨8, by decide⟩, true), (⟨10, by decide⟩, true), (⟨12, by decide⟩, true), (⟨14, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c6 : DefaultClause 16 := directClause [(⟨9, by decide⟩, false), (⟨10, by decide⟩, false), (⟨12, by decide⟩, false), (⟨13, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7 : DefaultClause 16 := directClause [(⟨7, by decide⟩, false), (⟨8, by decide⟩, false), (⟨12, by decide⟩, false), (⟨13, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c8 : DefaultClause 16 := directClause [(⟨9, by decide⟩, false), (⟨10, by decide⟩, false), (⟨14, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c9 : DefaultClause 16 := directClause [(⟨6, by decide⟩, true), (⟨8, by decide⟩, true), (⟨14, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c10 : DefaultClause 16 := directClause [(⟨6, by decide⟩, true), (⟨9, by decide⟩, true), (⟨13, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c11 : DefaultClause 16 := directClause [(⟨6, by decide⟩, false), (⟨10, by decide⟩, false), (⟨13, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c12 : DefaultClause 16 := directClause [(⟨8, by decide⟩, true), (⟨10, by decide⟩, true), (⟨11, by decide⟩, true), (⟨14, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c13 : DefaultClause 16 := directClause [(⟨9, by decide⟩, false), (⟨10, by decide⟩, false), (⟨11, by decide⟩, true), (⟨13, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c14 : DefaultClause 16 := directClause [(⟨6, by decide⟩, false), (⟨10, by decide⟩, false), (⟨11, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c15 : DefaultClause 16 := directClause [(⟨6, by decide⟩, false), (⟨7, by decide⟩, false), (⟨14, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c16 : DefaultClause 16 := directClause [(⟨6, by decide⟩, true), (⟨9, by decide⟩, true), (⟨12, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c17 : DefaultClause 16 := directClause [(⟨7, by decide⟩, true), (⟨9, by decide⟩, true), (⟨11, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c18 : DefaultClause 16 := directClause [(⟨7, by decide⟩, true), (⟨10, by decide⟩, true), (⟨11, by decide⟩, true), (⟨14, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c19 : DefaultClause 16 := directClause [(⟨9, by decide⟩, false), (⟨10, by decide⟩, false), (⟨11, by decide⟩, false), (⟨12, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c20 : DefaultClause 16 := directClause [(⟨6, by decide⟩, false), (⟨7, by decide⟩, false), (⟨11, by decide⟩, false), (⟨12, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c21 : DefaultClause 16 := directClause [(⟨6, by decide⟩, false), (⟨7, by decide⟩, false), (⟨13, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c22 : DefaultClause 16 := directClause [(⟨6, by decide⟩, true), (⟨8, by decide⟩, true), (⟨12, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c23 : DefaultClause 16 := directClause [(⟨7, by decide⟩, false), (⟨8, by decide⟩, false), (⟨11, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c24 : DefaultClause 16 := directClause [(⟨7, by decide⟩, true), (⟨10, by decide⟩, true), (⟨11, by decide⟩, true), (⟨13, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c25 : DefaultClause 16 := directClause [(⟨8, by decide⟩, true), (⟨10, by decide⟩, true), (⟨11, by decide⟩, false), (⟨12, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c26 : DefaultClause 16 := directClause [(⟨6, by decide⟩, false), (⟨7, by decide⟩, false), (⟨13, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c27 : DefaultClause 16 := directClause [(⟨6, by decide⟩, true), (⟨9, by decide⟩, true), (⟨12, by decide⟩, false), (⟨13, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c28 : DefaultClause 16 := directClause [(⟨7, by decide⟩, false), (⟨8, by decide⟩, false), (⟨11, by decide⟩, true), (⟨14, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c29 : DefaultClause 16 := directClause [(⟨7, by decide⟩, true), (⟨9, by decide⟩, true), (⟨11, by decide⟩, true), (⟨13, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c30 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨6, by decide⟩, false), (⟨12, by decide⟩, false), (⟨13, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c31 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨6, by decide⟩, false), (⟨12, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c32 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨6, by decide⟩, false), (⟨13, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c33 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨7, by decide⟩, false), (⟨11, by decide⟩, true), (⟨14, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c34 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨7, by decide⟩, false), (⟨11, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c35 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨7, by decide⟩, false), (⟨13, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c36 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨7, by decide⟩, false), (⟨13, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c37 : DefaultClause 16 := directClause [(⟨3, by decide⟩, false), (⟨8, by decide⟩, false), (⟨11, by decide⟩, false), (⟨12, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c38 : DefaultClause 16 := directClause [(⟨4, by decide⟩, false), (⟨9, by decide⟩, false), (⟨11, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c39 : DefaultClause 16 := directClause [(⟨4, by decide⟩, false), (⟨9, by decide⟩, false), (⟨12, by decide⟩, false), (⟨13, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c40 : DefaultClause 16 := directClause [(⟨4, by decide⟩, false), (⟨9, by decide⟩, false), (⟨13, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c41 : DefaultClause 16 := directClause [(⟨5, by decide⟩, false), (⟨10, by decide⟩, false), (⟨11, by decide⟩, true), (⟨14, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c42 : DefaultClause 16 := directClause [(⟨5, by decide⟩, false), (⟨10, by decide⟩, false), (⟨13, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c43 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨11, by decide⟩, false), (⟨7, by decide⟩, true), (⟨10, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c44 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨11, by decide⟩, false), (⟨9, by decide⟩, false), (⟨10, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c45 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨12, by decide⟩, false), (⟨6, by decide⟩, false), (⟨10, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c46 : DefaultClause 16 := directClause [(⟨3, by decide⟩, false), (⟨13, by decide⟩, false), (⟨7, by decide⟩, true), (⟨9, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c47 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨2, by decide⟩, false), (⟨14, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c48 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨2, by decide⟩, false), (⟨13, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c49 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨2, by decide⟩, false), (⟨13, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c50 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨2, by decide⟩, false), (⟨9, by decide⟩, false), (⟨10, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c51 : DefaultClause 16 := directClause [(⟨1, by decide⟩, true), (⟨3, by decide⟩, true), (⟨12, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c52 : DefaultClause 16 := directClause [(⟨1, by decide⟩, true), (⟨3, by decide⟩, true), (⟨7, by decide⟩, false), (⟨12, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c53 : DefaultClause 16 := directClause [(⟨1, by decide⟩, true), (⟨3, by decide⟩, true), (⟨7, by decide⟩, true), (⟨10, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c54 : DefaultClause 16 := directClause [(⟨1, by decide⟩, true), (⟨3, by decide⟩, true), (⟨9, by decide⟩, false), (⟨10, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c55 : DefaultClause 16 := directClause [(⟨1, by decide⟩, true), (⟨4, by decide⟩, true), (⟨13, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c56 : DefaultClause 16 := directClause [(⟨1, by decide⟩, true), (⟨4, by decide⟩, true), (⟨12, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c57 : DefaultClause 16 := directClause [(⟨1, by decide⟩, true), (⟨4, by decide⟩, true), (⟨12, by decide⟩, false), (⟨13, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c58 : DefaultClause 16 := directClause [(⟨1, by decide⟩, true), (⟨4, by decide⟩, true), (⟨10, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c59 : DefaultClause 16 := directClause [(⟨1, by decide⟩, true), (⟨4, by decide⟩, true), (⟨7, by decide⟩, true), (⟨10, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c60 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨5, by decide⟩, false), (⟨12, by decide⟩, false), (⟨13, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c61 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨5, by decide⟩, false), (⟨9, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c62 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨3, by decide⟩, false), (⟨11, by decide⟩, true), (⟨14, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c63 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨3, by decide⟩, false), (⟨10, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c64 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨3, by decide⟩, false), (⟨6, by decide⟩, true), (⟨9, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c65 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨3, by decide⟩, false), (⟨6, by decide⟩, false), (⟨10, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c66 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨3, by decide⟩, false), (⟨9, by decide⟩, false), (⟨10, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c67 : DefaultClause 16 := directClause [(⟨2, by decide⟩, true), (⟨4, by decide⟩, true), (⟨13, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c68 : DefaultClause 16 := directClause [(⟨2, by decide⟩, true), (⟨4, by decide⟩, true), (⟨11, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c69 : DefaultClause 16 := directClause [(⟨2, by decide⟩, true), (⟨4, by decide⟩, true), (⟨6, by decide⟩, false), (⟨11, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c70 : DefaultClause 16 := directClause [(⟨2, by decide⟩, true), (⟨5, by decide⟩, true), (⟨13, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c71 : DefaultClause 16 := directClause [(⟨2, by decide⟩, true), (⟨5, by decide⟩, true), (⟨11, by decide⟩, true), (⟨14, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c72 : DefaultClause 16 := directClause [(⟨2, by decide⟩, true), (⟨5, by decide⟩, true), (⟨6, by decide⟩, false), (⟨11, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c73 : DefaultClause 16 := directClause [(⟨2, by decide⟩, true), (⟨5, by decide⟩, true), (⟨9, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c74 : DefaultClause 16 := directClause [(⟨2, by decide⟩, true), (⟨5, by decide⟩, true), (⟨6, by decide⟩, true), (⟨8, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c75 : DefaultClause 16 := directClause [(⟨3, by decide⟩, false), (⟨4, by decide⟩, false), (⟨12, by decide⟩, true), (⟨15, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c76 : DefaultClause 16 := directClause [(⟨3, by decide⟩, false), (⟨4, by decide⟩, false), (⟨10, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c77 : DefaultClause 16 := directClause [(⟨3, by decide⟩, true), (⟨5, by decide⟩, true), (⟨11, by decide⟩, true), (⟨14, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c78 : DefaultClause 16 := directClause [(⟨3, by decide⟩, true), (⟨5, by decide⟩, true), (⟨6, by decide⟩, true), (⟨9, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c79 : DefaultClause 16 := directClause [(⟨4, by decide⟩, false), (⟨5, by decide⟩, false), (⟨11, by decide⟩, false), (⟨12, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c80 : DefaultClause 16 := directClause [(⟨1, by decide⟩, false), (⟨6, by decide⟩, false), (⟨11, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c81 : DefaultClause 16 := directClause [(⟨2, by decide⟩, false), (⟨7, by decide⟩, false), (⟨12, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c82 : DefaultClause 16 := directClause [(⟨4, by decide⟩, false), (⟨9, by decide⟩, false), (⟨14, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c83 : DefaultClause 16 := directClause [(⟨5, by decide⟩, false), (⟨10, by decide⟩, false), (⟨15, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def inputBlock0 : Array (DefaultClause 16) := #[c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47, c48, c49, c50, c51, c52, c53, c54, c55, c56, c57, c58, c59, c60, c61, c62, c63, c64, c65, c66, c67, c68, c69, c70, c71, c72, c73, c74, c75, c76, c77, c78, c79, c80, c81, c82, c83]

end CochromaticTwenty.Certificates.Z8DirectTriangleCycle5
