import MerLeanExperiment.CertificateKernel

/-! Generated from the actual pinned fixed_core0-trim CNF/LRAT data.
The generator is untrusted: every computation and inference is kernel checked. -/
namespace CochromaticTwenty.Certificates.FixedCore0
open Std.Sat Std.Tactic.BVDecide.LRAT Std.Tactic.BVDecide.LRAT.Internal
open CochromaticTwenty.CertificateKernel
set_option maxRecDepth 100000
set_option maxHeartbeats 10000000
def c7501 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨44, by decide⟩, false), (⟨46, by decide⟩, false), (⟨57, by decide⟩, false), (⟨59, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7502 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨44, by decide⟩, false), (⟨46, by decide⟩, false), (⟨59, by decide⟩, false), (⟨63, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7503 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨49, by decide⟩, false), (⟨52, by decide⟩, false), (⟨59, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7504 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨51, by decide⟩, true), (⟨52, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7505 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨52, by decide⟩, true), (⟨53, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7506 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨53, by decide⟩, true), (⟨55, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7507 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨55, by decide⟩, true), (⟨59, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7508 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨55, by decide⟩, true), (⟨61, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7509 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨51, by decide⟩, false), (⟨53, by decide⟩, false), (⟨59, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7510 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨52, by decide⟩, false), (⟨59, by decide⟩, false), (⟨61, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7511 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨53, by decide⟩, false), (⟨57, by decide⟩, false), (⟨59, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7512 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨53, by decide⟩, false), (⟨59, by decide⟩, false), (⟨61, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7513 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨54, by decide⟩, true), (⟨59, by decide⟩, true), (⟨60, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7514 : DefaultClause 65 := directClause [(⟨40, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨59, by decide⟩, false), (⟨61, by decide⟩, false), (⟨63, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7515 : DefaultClause 65 := directClause [(⟨41, by decide⟩, false), (⟨42, by decide⟩, false), (⟨46, by decide⟩, false), (⟨55, by decide⟩, false), (⟨63, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7516 : DefaultClause 65 := directClause [(⟨41, by decide⟩, false), (⟨43, by decide⟩, false), (⟨48, by decide⟩, false), (⟨49, by decide⟩, true), (⟨53, by decide⟩, true), (⟨63, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7517 : DefaultClause 65 := directClause [(⟨41, by decide⟩, false), (⟨43, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨52, by decide⟩, true), (⟨62, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7518 : DefaultClause 65 := directClause [(⟨41, by decide⟩, false), (⟨43, by decide⟩, false), (⟨48, by decide⟩, false), (⟨51, by decide⟩, true), (⟨52, by decide⟩, true), (⟨54, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7519 : DefaultClause 65 := directClause [(⟨41, by decide⟩, false), (⟨43, by decide⟩, false), (⟨48, by decide⟩, false), (⟨51, by decide⟩, false), (⟨55, by decide⟩, false), (⟨62, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7520 : DefaultClause 65 := directClause [(⟨41, by decide⟩, false), (⟨43, by decide⟩, false), (⟨48, by decide⟩, false), (⟨60, by decide⟩, false), (⟨61, by decide⟩, false), (⟨63, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7521 : DefaultClause 65 := directClause [(⟨41, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, false), (⟨54, by decide⟩, false), (⟨63, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7522 : DefaultClause 65 := directClause [(⟨41, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨55, by decide⟩, true), (⟨59, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7523 : DefaultClause 65 := directClause [(⟨41, by decide⟩, false), (⟨46, by decide⟩, false), (⟨48, by decide⟩, false), (⟨54, by decide⟩, true), (⟨59, by decide⟩, true), (⟨60, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7524 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨50, by decide⟩, true), (⟨52, by decide⟩, true), (⟨62, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7525 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨50, by decide⟩, false), (⟨56, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7526 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨50, by decide⟩, false), (⟨57, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7527 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨50, by decide⟩, false), (⟨63, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7528 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨52, by decide⟩, false), (⟨56, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7529 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨56, by decide⟩, true), (⟨57, by decide⟩, true), (⟨63, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7530 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨46, by decide⟩, false), (⟨50, by decide⟩, true), (⟨55, by decide⟩, true), (⟨59, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7531 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨46, by decide⟩, false), (⟨50, by decide⟩, false), (⟨57, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7532 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨46, by decide⟩, false), (⟨52, by decide⟩, false), (⟨56, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7533 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨46, by decide⟩, false), (⟨55, by decide⟩, false), (⟨63, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7534 : DefaultClause 65 := directClause [(⟨42, by decide⟩, false), (⟨44, by decide⟩, false), (⟨46, by decide⟩, false), (⟨56, by decide⟩, true), (⟨57, by decide⟩, true), (⟨63, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7535 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨45, by decide⟩, false), (⟨47, by decide⟩, false), (⟨50, by decide⟩, true), (⟨52, by decide⟩, true), (⟨62, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7536 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨45, by decide⟩, false), (⟨47, by decide⟩, false), (⟨51, by decide⟩, true), (⟨52, by decide⟩, true), (⟨57, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7537 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨45, by decide⟩, false), (⟨47, by decide⟩, false), (⟨52, by decide⟩, false), (⟨55, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7538 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨45, by decide⟩, false), (⟨47, by decide⟩, false), (⟨55, by decide⟩, true), (⟨56, by decide⟩, true), (⟨57, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7539 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨47, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨51, by decide⟩, true), (⟨61, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7540 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨47, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨52, by decide⟩, true), (⟨62, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7541 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨47, by decide⟩, false), (⟨48, by decide⟩, false), (⟨50, by decide⟩, true), (⟨55, by decide⟩, true), (⟨61, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7542 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨47, by decide⟩, false), (⟨48, by decide⟩, false), (⟨51, by decide⟩, false), (⟨55, by decide⟩, false), (⟨62, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7543 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨47, by decide⟩, false), (⟨48, by decide⟩, false), (⟨54, by decide⟩, false), (⟨55, by decide⟩, false), (⟨58, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7544 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨47, by decide⟩, false), (⟨48, by decide⟩, false), (⟨55, by decide⟩, true), (⟨56, by decide⟩, true), (⟨57, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7545 : DefaultClause 65 := directClause [(⟨43, by decide⟩, false), (⟨47, by decide⟩, false), (⟨48, by decide⟩, false), (⟨55, by decide⟩, true), (⟨57, by decide⟩, true), (⟨61, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7546 : DefaultClause 65 := directClause [(⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨47, by decide⟩, false), (⟨50, by decide⟩, true), (⟨55, by decide⟩, true), (⟨59, by decide⟩, true)] (by decide +kernel) (by decide +kernel)
def c7547 : DefaultClause 65 := directClause [(⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨47, by decide⟩, false), (⟨50, by decide⟩, false), (⟨57, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7548 : DefaultClause 65 := directClause [(⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨47, by decide⟩, false), (⟨52, by decide⟩, false), (⟨59, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7549 : DefaultClause 65 := directClause [(⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨47, by decide⟩, false), (⟨54, by decide⟩, false), (⟨55, by decide⟩, false), (⟨58, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def c7550 : DefaultClause 65 := directClause [(⟨44, by decide⟩, false), (⟨45, by decide⟩, false), (⟨47, by decide⟩, false), (⟨57, by decide⟩, false), (⟨62, by decide⟩, false), (⟨64, by decide⟩, false)] (by decide +kernel) (by decide +kernel)
def inputBlock30 : Array (DefaultClause 65) := #[c7501, c7502, c7503, c7504, c7505, c7506, c7507, c7508, c7509, c7510, c7511, c7512, c7513, c7514, c7515, c7516, c7517, c7518, c7519, c7520, c7521, c7522, c7523, c7524, c7525, c7526, c7527, c7528, c7529, c7530, c7531, c7532, c7533, c7534, c7535, c7536, c7537, c7538, c7539, c7540, c7541, c7542, c7543, c7544, c7545, c7546, c7547, c7548, c7549, c7550]

end CochromaticTwenty.Certificates.FixedCore0
